apiVersion: apps/v1
kind: Deployment

metadata:
  name: pokedex-api

spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-api
  template:
    metadata:
      labels:
        app: pokedex-api
    spec:
      containers:
        - image: ghcr.io/Sougoumay/pokedex:main
          imagePullPolicy: Always
          name: pokeapi
          ports:
            - containerPort: 3000
          envFrom:
            - conifMapKeyRef:
                name: pokedex-api-svc
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
