apiVersion: apps/v1
kind: Deployment

metadata:
  name: pokedex-api

spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-api
  template:
    metadata:
      labels:
        app: pokedex-api
    spec:
      containers:
        - image: ghcr.io/sougoumay/pokedex:main
          imagePullPolicy: Always
          name: pokeapi
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: pokedex-api-cm
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
