apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - svc.yaml
  - configmap.yaml
  - pre-sync-job.yaml
  - post-sync-job.yaml

images:
- name: ghcr.io/sougoumay/pokedex:main
  newName: ghcr.io/sougoumay/pokedex
  newTag: sha-4423edb