apiVersion: apps/v1
kind: Deployment

metadata:
  name: pokedex-api-instance

spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-api-instance
  template:
    metadata:
      labels:
        app: pokedex-api-instance
    spec:
      containers:
        - image: ghcr.io/sougoumay/pokedex:main
          imagePullPolicy: Always
          name: pokeapi
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: POKEDEX_START_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-instance-cm
                  key: POKEDEX_START_NUMBER
            - name: POKEDEX_END_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-instance-cm
                  key: POKEDEX_END_NUMBER
            - name: POKEDEX_NAME
              valueFrom:
                configMapKeyRef:
                  name: pokedex-instance-cm
                  key: POKEDEX_NAME

  
